version: '3'
services:
  webserver:
    container_name: woocommerce
    build: .
    volumes:
      - ./tmp/wordpress:/var/www/html
      - ./woocommerce-mondu:/var/www/html/wp-content/plugins/woocommerce-mondu
    links:
      - dbserver:mysql
    ports:
      - 8080:80
    environment:
  
      WP_DEBUG_DISPLAY: 1
      WP_DEBUG_LOG: 1
      WORDPRESS_WP_DEBUG: 1
      WP_DEBUG: 1
      WORDPRESS_DB_HOST: dbserver
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  dbserver:
    container_name: woo_mariadb
    image: mariadb
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
