version: '3'
services:
  webserver:
    container_name: woocommerce
    image: shipbeat/woocommerce
    links:
      - dbserver:mysql
    ports:
      - 8080:80
    environment:
      - WORDPRESS_WP_DEBUG="false"
      - WORDPRESS_DB_HOST=dbserver
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_PORT=3306

  dbserver:
    container_name: woo_mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
