name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  code_quality_phpmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Install PHPMD
        run: composer require --dev phpmd/phpmd

      - name: Run PHPMD
        run: vendor/bin/phpmd path/to/your/plugin text cleancode,codesize,controversial,design,naming,unusedcode

  code_quality_phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse path/to/your/plugin --level=max

  code_quality_phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install PHPCS
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require "wp-coding-standards/wpcs=*"

      - name: Add composer global bin to PATH
        run: echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Run PHPCS
        run: phpcs --standard=WordPress